### ISSUE TITLE
Dividing the route for multiple drones

### ISSUE THREAD

**Issue by Bera0422** [cmpe-DroneLab/GeoFly3D#16]
- [x] The created route nodes for a given area should be divided according to the number of drones registered.

- [x] These divided routes should be assigned to relevant drones.

**Comment by AliNasra** [comment]
We are currently proceeding with Şahin's algorithm. Nevertheless, we are still in dire need of completing the optimization function in #24 before declaring this issue resolved.

**Comment by Bera0422** [comment]
We can close this issues as this algorithm is already implemented.
