### ISSUE TITLE
UI should support multi-drone feature

### ISSUE THREAD

**Issue by Bera0422** [cmpe-DroneLab/GeoFly3D#18]
- [x] Information regarding the estimated mission should be updated accordingly.
- [x] Route visualization should be updated according to division.
- [x] Real-time drone tracking should be updated accordingly.

**Comment by higurbuzz** [comment]
Now, we can track more than one drone on the map.

**Comment by higurbuzz** [comment]
Multipath visualization supported https://github.com/cmpe-DroneLab/GeoFly3D/commit/82bf2204d4a59e21df3d989ad6e5be87009a9eeb
