### ISSUE TITLE
Realtime Battery Tracking on Midflight

### ISSUE THREAD

**Issue by higurbuzz** [cmpe-DroneLab/GeoFly3D#31]
### Description

In addition to realtime GPS tracking on midflight screen, the app should also provide realtime battery tracking.

### Steps

- [x] Provide battery information
- [x] Display battery information

**Comment by higurbuzz** [comment]
Displaying battery information is implemented at https://github.com/cmpe-DroneLab/GeoFly3D/commit/e00fb226290df08660bb2d84c1f680d9325cc3a1

**Comment by Bera0422** [comment]
Implemented the backend mechanism. The battery information is stored as "battery_percent" in the geojson file.

**Comment by higurbuzz** [comment]
Since all tasks are completed, I am closing the issue.
