### ISSUE TITLE
Research Paper Analysis and discussion

### ISSUE THREAD

**Issue by AliNasra** [cmpe-DroneLab/GeoFly3D#8]
Birkan Hoca has forwarded [a research paper](https://scholar.google.com/scholar_url?url=https://www.techrxiv.org/articles/preprint/Differentiation_and_Localization_of_Ground_RF_Transmitters_Through_RSSI_Measures_from_a_UAV/24494845/1/files/43033000.pdf&hl=en&sa=X&d=14836274505825438620&ei=zOdYZdvzKpqa6rQP1YWcsA4&scisig=AFWwaeYRfN5pS8CCeIHAWqfyB60s&oi=scholaralrt&hist=Eg_wBXUAAAAJ:17253066771669113187:AFWwaeasHNw9yxnsvuEtLuXvyzUg&html=&pos=0&folt=art) which he believes would be beneficial for the project's development. Subsequently, all the team members are advised to read the document and take notes of any points of interest.

**Comment by Bera0422** [comment]
We have talked about the research paper in the meeting on 24.11.2023
